# Generated by Django 3.0.7 on 2022-09-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula'), ('TI', 'Tarjeta Identidad')], default='CC', max_length=2)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo_rol', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('activo', models.CharField(choices=[('on', 'Activo'), ('off', 'Inactivo')], default='on', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('especialidad', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital_en_casa.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cargo', models.CharField(max_length=45)),
                ('fecha_contrato', models.DateField()),
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital_en_casa.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('parentesco', models.CharField(max_length=45)),
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital_en_casa.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('georreferencia', models.CharField(max_length=45)),
                ('especialidad_doctor', models.CharField(max_length=30)),
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital_en_casa.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_en_casa.Rol'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital_en_casa.Paciente')),
                ('codigo', models.PositiveIntegerField()),
                ('en_cuidado', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=45)),
                ('recomendaciones', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_en_casa.Doctor')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_en_casa.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
                ('frecuencia_cardica', models.CharField(max_length=45)),
                ('temperatura', models.CharField(max_length=45)),
                ('presion_arterial', models.CharField(max_length=45)),
                ('glicemia', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('historico_Paciente_Doctor_especialidad', models.CharField(max_length=30)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_en_casa.Paciente')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_en_casa.Historico')),
            ],
        ),
    ]
