# Generated by Django 3.0.7 on 2022-09-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_en_casa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_medico',
            fields=[
                ('anio_contrato', models.IntegerField()),
                ('especialidad', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital_en_casa.Persona')),
            ],
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Auxiliar',
        ),
        migrations.AlterField(
            model_name='historico',
            name='en_cuidado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sugerencias',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_en_casa.Personal_medico'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
